/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse.inventory.view.main;

import java.awt.Color;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import edu.ijse.gdse.inventory.view.forms.DashBoardForm;
import edu.ijse.gdse.inventory.view.forms.NewItemForm;
import edu.ijse.gdse.inventory.view.forms.NewVendorForm;
import edu.ijse.gdse.inventory.view.forms.ReportsForm;
import edu.ijse.gdse.inventory.view.forms.SaleItemForm;
import edu.ijse.gdse.inventory.view.smallforms.Settings;

import javax.swing.JOptionPane;

/**
 *
 * @author Pahansith
 */
public class HomeForm extends javax.swing.JFrame {


    public static void addComponentToMajorOptionsPanel(Component component) {
        formsPanel.removeAll();
        formsPanel.add(component);
        formsPanel.revalidate();
    }
    
    public static void setVendorForm(){
        NewVendorForm form = new NewVendorForm();
        formsPanel.removeAll();
        formsPanel.add(form);
        formsPanel.revalidate();
    }

    public static Component getInstance() {
        return new HomeForm();
    }
    
    public HomeForm() {
        initComponents();
        setDashboard();
    }

    private void setDashboard() {
        formsPanel.removeAll();
        DashBoardForm form = new DashBoardForm();
        formsPanel.add(form);
        formsPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formsPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        loggedUserNameLabel = new javax.swing.JLabel();
        settingsLabel = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        inventoryPanel = new javax.swing.JPanel();
        inventortyIconPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        inventoryTextPanel = new javax.swing.JPanel();
        inventoryTextLabel = new javax.swing.JLabel();
        vendorPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        vendorTextLabel = new javax.swing.JLabel();
        salePanel = new javax.swing.JPanel();
        saleIconPanel = new javax.swing.JPanel();
        saleIconLabel = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        saleLabel = new javax.swing.JLabel();
        reportsPanel = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        dashBoardPanel = new javax.swing.JPanel();
        dashBoardIconPanel = new javax.swing.JPanel();
        dashBoardImageLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        dashBoardTextPanel = new javax.swing.JPanel();
        dashboardTextLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(30, 40));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 242, 240));
        jPanel1.setLayout(null);

        formsPanel.setBackground(new java.awt.Color(242, 242, 240));
        formsPanel.setLayout(new java.awt.GridLayout(0, 1));
        jPanel1.add(formsPanel);
        formsPanel.setBounds(250, 90, 1120, 645);

        jPanel2.setBackground(new java.awt.Color(55, 55, 55));
        jPanel2.setForeground(new java.awt.Color(55, 55, 55));

        jPanel3.setBackground(new java.awt.Color(55, 55, 55));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Label.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(39, 39, 39));
        jPanel4.setMinimumSize(new java.awt.Dimension(223, 70));
        jPanel4.setPreferredSize(new java.awt.Dimension(223, 70));
        jPanel4.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userIcon.png"))); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 20, 50, 48);

        loggedUserNameLabel.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        loggedUserNameLabel.setForeground(new java.awt.Color(195, 195, 195));
        loggedUserNameLabel.setText("THARAKA FDO");
        jPanel4.add(loggedUserNameLabel);
        loggedUserNameLabel.setBounds(70, 20, 100, 50);

        settingsLabel.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        settingsLabel.setForeground(new java.awt.Color(195, 195, 195));
        settingsLabel.setText("Settings");
        settingsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsLabelMouseClicked(evt);
            }
        });

        closeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(195, 195, 195));
        closeLabel.setText("X");
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 907, Short.MAX_VALUE)
                .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(closeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 90);

        menuPanel.setBackground(new java.awt.Color(242, 242, 234));
        menuPanel.setLayout(null);

        inventoryPanel.setLayout(null);

        inventortyIconPanel.setBackground(new java.awt.Color(242, 242, 234));
        inventortyIconPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        inventortyIconPanel.setMinimumSize(new java.awt.Dimension(60, 60));
        inventortyIconPanel.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventoryIcon.png"))); // NOI18N
        inventortyIconPanel.add(jLabel9);
        jLabel9.setBounds(10, 10, 40, 40);

        jPanel19.setBackground(new java.awt.Color(65, 175, 75));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        inventortyIconPanel.add(jPanel19);
        jPanel19.setBounds(0, 0, 4, 60);

        inventoryPanel.add(inventortyIconPanel);
        inventortyIconPanel.setBounds(0, 0, 60, 60);

        inventoryTextPanel.setBackground(new java.awt.Color(242, 242, 234));
        inventoryTextPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        inventoryTextPanel.setMinimumSize(new java.awt.Dimension(160, 60));

        inventoryTextLabel.setBackground(new java.awt.Color(242, 242, 234));
        inventoryTextLabel.setFont(new java.awt.Font("Open Sans Extrabold", 0, 14)); // NOI18N
        inventoryTextLabel.setForeground(new java.awt.Color(113, 112, 110));
        inventoryTextLabel.setText("   INVENTORY");
        inventoryTextLabel.setOpaque(true);
        inventoryTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryTextLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout inventoryTextPanelLayout = new javax.swing.GroupLayout(inventoryTextPanel);
        inventoryTextPanel.setLayout(inventoryTextPanelLayout);
        inventoryTextPanelLayout.setHorizontalGroup(
            inventoryTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inventoryTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        inventoryTextPanelLayout.setVerticalGroup(
            inventoryTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inventoryTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        inventoryPanel.add(inventoryTextPanel);
        inventoryTextPanel.setBounds(60, 0, 190, 60);

        menuPanel.add(inventoryPanel);
        inventoryPanel.setBounds(0, 120, 250, 60);

        vendorPanel.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(242, 242, 234));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        jPanel8.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel8.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel8.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vendor.png"))); // NOI18N
        jPanel8.add(jLabel5);
        jLabel5.setBounds(10, 10, 40, 40);

        jPanel18.setBackground(new java.awt.Color(43, 87, 154));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel18);
        jPanel18.setBounds(0, 0, 4, 60);

        vendorPanel.add(jPanel8);
        jPanel8.setBounds(0, 0, 60, 60);

        jPanel9.setBackground(new java.awt.Color(242, 242, 234));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        jPanel9.setMinimumSize(new java.awt.Dimension(160, 60));
        jPanel9.setPreferredSize(new java.awt.Dimension(160, 60));

        vendorTextLabel.setBackground(new java.awt.Color(242, 242, 234));
        vendorTextLabel.setFont(new java.awt.Font("Open Sans Extrabold", 0, 14)); // NOI18N
        vendorTextLabel.setForeground(new java.awt.Color(113, 112, 110));
        vendorTextLabel.setText("   VENDORS");
        vendorTextLabel.setOpaque(true);
        vendorTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendorTextLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vendorTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vendorTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        vendorPanel.add(jPanel9);
        jPanel9.setBounds(60, 0, 190, 60);

        menuPanel.add(vendorPanel);
        vendorPanel.setBounds(0, 60, 250, 60);

        salePanel.setLayout(null);

        saleIconPanel.setBackground(new java.awt.Color(242, 242, 234));
        saleIconPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        saleIconPanel.setMinimumSize(new java.awt.Dimension(60, 60));
        saleIconPanel.setLayout(null);

        saleIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saleIcon.png"))); // NOI18N
        saleIconPanel.add(saleIconLabel);
        saleIconLabel.setBounds(10, 10, 40, 40);

        jPanel21.setBackground(new java.awt.Color(96, 113, 219));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        saleIconPanel.add(jPanel21);
        jPanel21.setBounds(0, 0, 4, 60);

        salePanel.add(saleIconPanel);
        saleIconPanel.setBounds(0, 0, 60, 60);

        jPanel15.setBackground(new java.awt.Color(242, 242, 234));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        jPanel15.setMinimumSize(new java.awt.Dimension(160, 60));

        saleLabel.setBackground(new java.awt.Color(242, 242, 234));
        saleLabel.setFont(new java.awt.Font("Open Sans Extrabold", 0, 14)); // NOI18N
        saleLabel.setForeground(new java.awt.Color(113, 112, 110));
        saleLabel.setText("   SALE");
        saleLabel.setOpaque(true);
        saleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        salePanel.add(jPanel15);
        jPanel15.setBounds(60, 0, 190, 60);

        menuPanel.add(salePanel);
        salePanel.setBounds(0, 180, 250, 60);

        reportsPanel.setLayout(null);

        jPanel16.setBackground(new java.awt.Color(242, 242, 234));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        jPanel16.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel16.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reportsIcon.png"))); // NOI18N
        jPanel16.add(jLabel14);
        jLabel14.setBounds(10, 10, 40, 40);

        jPanel22.setBackground(new java.awt.Color(169, 111, 110));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel22);
        jPanel22.setBounds(0, 0, 4, 60);

        reportsPanel.add(jPanel16);
        jPanel16.setBounds(0, 0, 60, 60);

        jPanel17.setBackground(new java.awt.Color(242, 242, 234));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        jPanel17.setMinimumSize(new java.awt.Dimension(160, 60));

        jLabel15.setBackground(new java.awt.Color(242, 242, 234));
        jLabel15.setFont(new java.awt.Font("Open Sans Extrabold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(113, 112, 110));
        jLabel15.setText("   REPORTS");
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        reportsPanel.add(jPanel17);
        jPanel17.setBounds(60, 0, 190, 60);

        menuPanel.add(reportsPanel);
        reportsPanel.setBounds(0, 240, 250, 60);

        dashBoardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashBoardPanelMouseEntered(evt);
            }
        });
        dashBoardPanel.setLayout(null);

        dashBoardIconPanel.setBackground(new java.awt.Color(242, 242, 234));
        dashBoardIconPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        dashBoardIconPanel.setLayout(null);

        dashBoardImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        dashBoardIconPanel.add(dashBoardImageLabel);
        dashBoardImageLabel.setBounds(10, 10, 40, 40);

        jPanel7.setBackground(new java.awt.Color(222, 98, 98));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        dashBoardIconPanel.add(jPanel7);
        jPanel7.setBounds(0, 0, 4, 60);

        dashBoardPanel.add(dashBoardIconPanel);
        dashBoardIconPanel.setBounds(0, 0, 60, 60);

        dashBoardTextPanel.setBackground(new java.awt.Color(242, 242, 234));
        dashBoardTextPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        dashBoardTextPanel.setMinimumSize(new java.awt.Dimension(160, 60));

        dashboardTextLabel.setBackground(new java.awt.Color(242, 242, 234));
        dashboardTextLabel.setFont(new java.awt.Font("Open Sans Extrabold", 0, 14)); // NOI18N
        dashboardTextLabel.setForeground(new java.awt.Color(113, 112, 110));
        dashboardTextLabel.setText("   DASHBOARD");
        dashboardTextLabel.setOpaque(true);
        dashboardTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardTextLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dashBoardTextPanelLayout = new javax.swing.GroupLayout(dashBoardTextPanel);
        dashBoardTextPanel.setLayout(dashBoardTextPanelLayout);
        dashBoardTextPanelLayout.setHorizontalGroup(
            dashBoardTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        dashBoardTextPanelLayout.setVerticalGroup(
            dashBoardTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        dashBoardPanel.add(dashBoardTextPanel);
        dashBoardTextPanel.setBounds(60, 0, 190, 60);

        menuPanel.add(dashBoardPanel);
        dashBoardPanel.setBounds(0, 0, 250, 60);

        jPanel6.setBackground(new java.awt.Color(242, 242, 234));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 229, 208)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        menuPanel.add(jPanel6);
        jPanel6.setBounds(-10, 300, 260, 360);

        jPanel1.add(menuPanel);
        menuPanel.setBounds(0, 90, 251, 650);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vendorTextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorTextLabelMouseClicked
        NewVendorForm form = new NewVendorForm();
        formsPanel.removeAll();
        formsPanel.add(form);
        formsPanel.repaint();
        formsPanel.revalidate();
    }//GEN-LAST:event_vendorTextLabelMouseClicked

    private void inventoryTextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTextLabelMouseClicked
        NewItemForm form = new NewItemForm();
        formsPanel.removeAll();
        formsPanel.add(form);
        formsPanel.revalidate();
        
    }//GEN-LAST:event_inventoryTextLabelMouseClicked

    private void dashboardTextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardTextLabelMouseClicked
        //saleIconPanel.setBackground(new Color(96,113,219));
        //saleIconLabel.setIcon(new ImageIcon(getClass().getResource("/images/saleWhite.png")));
        formsPanel.removeAll();
        DashBoardForm form = new DashBoardForm();
        formsPanel.add(form);
        formsPanel.revalidate();
    }//GEN-LAST:event_dashboardTextLabelMouseClicked

    private void saleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleLabelMouseClicked
        formsPanel.removeAll();
        SaleItemForm sale = new SaleItemForm();
        formsPanel.add(sale);
        formsPanel.revalidate();
    }//GEN-LAST:event_saleLabelMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        formsPanel.removeAll();
        ReportsForm report = new ReportsForm();
        formsPanel.add(report);
        formsPanel.revalidate();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        Object[] values = {"Yes","No","Cancel"};
        int option = JOptionPane.showConfirmDialog(HomeForm.this, "Are you sure you want to exit?", "Confirm Action", JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_closeLabelMouseClicked

    private void dashBoardPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashBoardPanelMouseEntered
        dashBoardPanel.setBackground(new Color(247,246,209));
    }//GEN-LAST:event_dashBoardPanelMouseEntered

    private void settingsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsLabelMouseClicked
        new Settings().setVisible(true);
    }//GEN-LAST:event_settingsLabelMouseClicked

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> {
            new HomeForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeLabel;
    private javax.swing.JPanel dashBoardIconPanel;
    private javax.swing.JLabel dashBoardImageLabel;
    private javax.swing.JPanel dashBoardPanel;
    private javax.swing.JPanel dashBoardTextPanel;
    private javax.swing.JLabel dashboardTextLabel;
    private static javax.swing.JPanel formsPanel;
    private javax.swing.JPanel inventortyIconPanel;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JLabel inventoryTextLabel;
    private javax.swing.JPanel inventoryTextPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel loggedUserNameLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel reportsPanel;
    private javax.swing.JLabel saleIconLabel;
    private javax.swing.JPanel saleIconPanel;
    private javax.swing.JLabel saleLabel;
    private javax.swing.JPanel salePanel;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JPanel vendorPanel;
    private javax.swing.JLabel vendorTextLabel;
    // End of variables declaration//GEN-END:variables
    
    public static JPanel getFormsPanelInstance(){
        return formsPanel;
    }
    
    public void setUserName(String userName){
        loggedUserNameLabel.setText(userName);
    }
   
}
