/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse.inventory.view.smallforms;

import edu.ijse.gdse.inventory.controller.TaxSchemeController;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import edu.ijse.gdse.inventory.model.TaxScheme;
import edu.ijse.gdse.inventory.other.TextFieldHandler;
import edu.ijse.gdse.inventory.view.forms.NewVendorForm;

/**
 *
 * @author Pahansith
 */
public class NewTaxSchemeForm extends javax.swing.JFrame {
    
    private static NewVendorForm motherForm;
    private DefaultComboBoxModel idComboModel;
    private boolean addPressed = false;
    private boolean isTextEntered;
    /**
     * Creates new form NewTaxSchemeForm
     */
    public NewTaxSchemeForm() {
        initComponents();
        setTaxIdCombo();
        setDefaults();
        setFrameValues();
   
    }

    

    public NewTaxSchemeForm(NewVendorForm motherForm) {
        this();
        this.motherForm = motherForm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idCombo = new javax.swing.JComboBox<>();
        categoryText = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        taxRateText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    Manage Tax Schemes");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Scheme");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Category");

        idCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idComboItemStateChanged(evt);
            }
        });

        categoryText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                categoryTextKeyTyped(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add New");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Rate");

        taxRateText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                taxRateTextKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ID");

        idText.setEditable(false);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(taxRateText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryText, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categoryText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(taxRateText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(491, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            boolean isDeleted = TaxSchemeController.deleteTaxScheme(idText.getText());
            if (isDeleted) {
                setTaxIdCombo();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewTaxSchemeForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(NewTaxSchemeForm.this, "You Cannot Delete This Scheme");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void taxRateTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taxRateTextKeyTyped
        isTextEntered = true;
        if(!addPressed){
            addButton.setText("Update");
        }
    }//GEN-LAST:event_taxRateTextKeyTyped

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            if (!addPressed) {
                if (!isTextEntered) {
                    addButton.setText("Save");
                    setDefaults();
                    setNextTaxId();
                    idCombo.setEnabled(false);
                    addPressed = true;
                } else {
                    boolean isUpdated = TaxSchemeController.updateTaxScheme(getFormDetails());
                    if(isUpdated){
                        isTextEntered = false;
                        addButton.setText("Add New");
                        setDefaults();
                        setTaxIdCombo();
                    }
                }
            } else {
                boolean isAdded = TaxSchemeController.addNewTaxScheme(getFormDetails());
                if (isAdded) {
                    addButton.setText("Add New");
                    idCombo.setEnabled(true);
                    addPressed = false;
                    setTaxIdCombo();
                    setDefaults();
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewTaxSchemeForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewTaxSchemeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        
        motherForm.loadTaxCombo();
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void categoryTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categoryTextKeyTyped
        isTextEntered = true;
        if(!addPressed){
            addButton.setText("Update");
        }
    }//GEN-LAST:event_categoryTextKeyTyped

    private void idComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idComboItemStateChanged
        if (idCombo.getSelectedItem() != null) {
            try {
                String nextTaxId = TaxSchemeController.getNextTaxId();
                idText.setText(nextTaxId);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewTaxSchemeForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(NewTaxSchemeForm.class.getName()).log(Level.SEVERE, null, ex);
            }

            TaxScheme selectedScheme = (TaxScheme) idCombo.getSelectedItem();
            categoryText.setText(selectedScheme.getTaxCategory());
            taxRateText.setText(Double.toString(selectedScheme.getTaxRate()));
            idText.setText(selectedScheme.getTaxId());
        }
    }//GEN-LAST:event_idComboItemStateChanged

    private TaxScheme getFormDetails() throws NumberFormatException {
        TaxScheme scheme = new TaxScheme();
        if (isAllFilled()) {
            scheme.setTaxId(idText.getText());
            scheme.setTaxCategory(categoryText.getText());
            scheme.setTaxRate(Double.parseDouble(taxRateText.getText()));
        }else{
            JOptionPane.showMessageDialog(NewTaxSchemeForm.this, "Please Fill All");
        }
        
        return scheme;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(NewTaxSchemeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewTaxSchemeForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField categoryText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> idCombo;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField taxRateText;
    // End of variables declaration//GEN-END:variables

    private void setTaxIdCombo() {
        idCombo.removeAllItems();
        idComboModel = (DefaultComboBoxModel) idCombo.getModel();
        try {
            ArrayList<TaxScheme> allTaxScehemes = TaxSchemeController.getAllTaxScehemes();
            for (TaxScheme scheme : allTaxScehemes) {
                idComboModel.addElement(scheme);
            }
            setDefaults();
        } catch (SQLException ex) {
            Logger.getLogger(NewTaxSchemeForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewTaxSchemeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setDefaults() {
        idCombo.setSelectedIndex(-1);
        idText.setText(null);
        categoryText.setText(null);
        taxRateText.setText(null);
    }

    private void setNextTaxId() {
        try {
            String nextTaxId = TaxSchemeController.getNextTaxId();
            idText.setText(nextTaxId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewTaxSchemeForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewTaxSchemeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private boolean isAllFilled(){
        return TextFieldHandler.isAllTextFieldsFilled(categoryText,taxRateText);
    }
    
    private void setFrameValues() {
        getContentPane().setBackground(new Color(0.5f, 0.5f, 0.5f, 0.5f));
        setBackground(new Color(0.5f, 0.5f, 0.5f, 0.5f));
    }
}
