/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse.inventory.view.smallforms;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JRViewer;
import edu.ijse.gdse.inventory.view.forms.PurchaseInvoiceForm;

/**
 *
 * @author Pahansith
 */
public class PrintInvoicePreviewForm extends javax.swing.JFrame {
    
    private static PurchaseInvoiceForm motherForm;
    private DefaultTableModel model;
    private JasperPrint filledReport;
    /**
     * Creates new form NewTaxSchemeForm
     */
    public PrintInvoicePreviewForm() {
        initComponents();
        setFrameValues();
   
    }

    

    public PrintInvoicePreviewForm(PurchaseInvoiceForm motherForm,JasperPrint filledReport) {
        this();
        PrintInvoicePreviewForm.motherForm = motherForm;
        generatePreview(filledReport);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        printPreviewHost = new javax.swing.JPanel();
        printLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    Print Preview");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1270, 29);

        printPreviewHost.setBackground(new java.awt.Color(255, 255, 255));
        printPreviewHost.setLayout(null);
        jPanel1.add(printPreviewHost);
        printPreviewHost.setBounds(10, 35, 1230, 510);

        printLabel.setBackground(new java.awt.Color(65, 175, 75));
        printLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printLabel.setForeground(new java.awt.Color(255, 255, 255));
        printLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printLabel.setText("Print");
        printLabel.setOpaque(true);
        printLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printLabelMouseClicked(evt);
            }
        });
        jPanel1.add(printLabel);
        printLabel.setBounds(990, 550, 118, 32);

        cancelButton.setBackground(new java.awt.Color(68, 106, 129));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelButton.setText("Cancel");
        cancelButton.setOpaque(true);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cancelButton);
        cancelButton.setBounds(1130, 550, 118, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 50, 1270, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printLabelMouseClicked
        try {
            boolean isPrinted = JasperPrintManager.printReport(filledReport, true);
        } catch (JRException ex) {
            Logger.getLogger(PrintInvoicePreviewForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printLabelMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PrintInvoicePreviewForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PrintInvoicePreviewForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel printLabel;
    private javax.swing.JPanel printPreviewHost;
    // End of variables declaration//GEN-END:variables

   
    private void setFrameValues() {
        getContentPane().setBackground(new Color(0.5f, 0.5f, 0.5f, 0.5f));
        setBackground(new Color(0.5f, 0.5f, 0.5f, 0.5f));
    }

    private void generatePreview(JasperPrint filledReport) {
        this.filledReport = filledReport;
        JRViewer jrViewer = new JRViewer(filledReport);
        
        jrViewer.setBounds(0,0,printPreviewHost.getWidth(),printPreviewHost.getHeight());
        printPreviewHost.removeAll();
        printPreviewHost.add(jrViewer);
        printPreviewHost.repaint();
        printPreviewHost.revalidate();
    }
}
