/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse.inventory.view.smallforms;

import edu.ijse.gdse.inventory.db.DBConnection;
import java.awt.Color;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRViewer;
import edu.ijse.gdse.inventory.view.forms.SaleItemForm;
import edu.ijse.gdse.inventory.view.main.HomeForm;

/**
 *
 * @author Pahansith
 */
public class PrintBillPreview extends javax.swing.JFrame {
    private SaleItemForm motherForm;
    private double totalAmount;
    private String billNumber;
    private DefaultTableModel tableModel;
    private JasperPrint fillReport;
    /**
     * Creates new form NewTaxSchemeForm
     */
    public PrintBillPreview() {
        initComponents();
        setFrameValues();
        
    }
   
    public PrintBillPreview(SaleItemForm motherForm,double totalAmount,String billNumber){
        this();
        this.motherForm = motherForm;
        this.totalAmount = totalAmount;
        this.billNumber = billNumber;
        setPreview();
    }
    

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        billPreviewHost = new javax.swing.JPanel();
        printBillLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    Bill Print Preview");
        jLabel1.setOpaque(true);

        billPreviewHost.setBackground(new java.awt.Color(255, 255, 255));
        billPreviewHost.setLayout(null);

        printBillLabel.setBackground(new java.awt.Color(65, 175, 75));
        printBillLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printBillLabel.setForeground(new java.awt.Color(255, 255, 255));
        printBillLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printBillLabel.setText("Print Bill");
        printBillLabel.setOpaque(true);
        printBillLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printBillLabelMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(68, 106, 129));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cancel");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(billPreviewHost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(printBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billPreviewHost, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printBillLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBillLabelMouseClicked
        try {
            JasperPrintManager.printReport(fillReport, true);
            setNewSellItem();
            this.dispose();
            
        } catch (JRException ex) {
            Logger.getLogger(PrintBillPreview.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printBillLabelMouseClicked

    private void setNewSellItem() {
        SaleItemForm saleForm = new SaleItemForm();
        JPanel formsPanelInstance = HomeForm.getFormsPanelInstance();
        formsPanelInstance.removeAll();
        formsPanelInstance.add(saleForm);
        formsPanelInstance.repaint();
        formsPanelInstance.revalidate();
    }

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        setNewSellItem();
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PrintBillPreview.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PrintBillPreview().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel billPreviewHost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel printBillLabel;
    // End of variables declaration//GEN-END:variables

   
    private void setFrameValues() {
        getContentPane().setBackground(new Color(0.5f, 0.5f, 0.5f, 0.5f));
        setBackground(new Color(0.5f, 0.5f, 0.5f, 0.5f));
    }

    private void setPreview() {
        try {
            HashMap<String,Object> map = new HashMap<>();
            map.put("BillNumber",billNumber);
            map.put("TotalAmount",totalAmount);
            
            Connection conn = DBConnection.getDBConnection().getConnection();
            InputStream file = getClass().getResourceAsStream("/edu/ijse/gdse/inventory/jasperreports/SaleBill.jrxml");
            JasperReport compileReport = JasperCompileManager.compileReport(file);
            
            fillReport = JasperFillManager.fillReport(compileReport, map, conn);
            
            JRViewer jrViewer = new JRViewer(fillReport);
            jrViewer.setBounds(0, 0, billPreviewHost.getWidth(), billPreviewHost.getHeight());
            billPreviewHost.add(jrViewer);
            billPreviewHost.repaint();
            billPreviewHost.revalidate();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrintBillPreview.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PrintBillPreview.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(PrintBillPreview.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
