/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse.inventory.view.smallforms;

import edu.ijse.gdse.inventory.view.forms.SaleItemForm;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import edu.ijse.gdse.inventory.model.helper.SelectedItem;

/**
 *
 * @author Pahansith
 */
public class SelectedItemPanel extends javax.swing.JPanel {
    
    public class MouseClicked extends MouseAdapter{

        @Override
        public void mouseClicked(MouseEvent e) {

            String itemCode = getItemCode();
            String description = getDescription();
            double soldPrice = getSoldPrice();
            int soldQty = getSoldQty();
            double discount = getDiscount();
            SelectedItem item = new SelectedItem(itemCode, description, soldPrice, soldQty, discount);

            SaleItemForm.setSelectItemDetails(item,SelectedItemPanel.this);

        }

}
    
    private String itemCode;
    private String description;
    private double soldPrice;
    private int soldQty;
    private double discount;
    /**
     * Creates new form ItemMiniPanel
     */
    public SelectedItemPanel() {
        initComponents();
        MouseClicked mouseClicked = new MouseClicked();
        addMouseListener(mouseClicked);
    }
    
    public SelectedItemPanel(String itemCode,String description, double soldPrice, int soldQty,double discount, int x, int y){
        this();
        setBounds(x, y, 120, 120);
        itemNameLabel.setText(description);
        priceLabel.setText("Rs "+Double.toString(soldPrice));
        orderQtyLabel.setText(Integer.toString(soldQty));
        this.itemCode = itemCode;
        this.description = description;
        this.soldPrice = soldPrice;
        this.soldQty = soldQty;
        this.discount = discount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderQtyLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        itemNameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 180, 199)));
        setLayout(null);

        orderQtyLabel.setFont(new java.awt.Font("Open Sans Extrabold", 0, 12)); // NOI18N
        orderQtyLabel.setForeground(new java.awt.Color(193, 186, 171));
        orderQtyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(orderQtyLabel);
        orderQtyLabel.setBounds(40, 70, 40, 20);

        jPanel1.setBackground(new java.awt.Color(100, 180, 199));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 130, 10);

        itemNameLabel.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        itemNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        itemNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemNameLabel.setText("qwertyuiopasdfghj");
        itemNameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemNameLabelMouseClicked(evt);
            }
        });
        add(itemNameLabel);
        itemNameLabel.setBounds(0, 10, 120, 40);

        priceLabel.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(0, 51, 255));
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(priceLabel);
        priceLabel.setBounds(0, 90, 120, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void itemNameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemNameLabelMouseClicked
        MouseClicked mouseClicked = new MouseClicked();
        mouseClicked.mouseClicked(evt);
    }//GEN-LAST:event_itemNameLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel orderQtyLabel;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables


    /**
     * @return the itemCode
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the soldPrice
     */
    public double getSoldPrice() {
        return soldPrice;
    }

    /**
     * @param soldPrice the soldPrice to set
     */
    public void setSoldPrice(double soldPrice) {
        this.soldPrice = soldPrice;
    }

    /**
     * @return the soldQty
     */
    public int getSoldQty() {
        return soldQty;
    }

    /**
     * @param soldQty the soldQty to set
     */
    public void setSoldQty(int soldQty) {
        this.soldQty = soldQty;
    }

    /**
     * @return the discount
     */
    public double getDiscount() {
        return discount;
    }

    /**
     * @param discount the discount to set
     */
    public void setDiscount(double discount) {
        this.discount = discount;
    }

}
