/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse.inventory.view.forms;

import edu.ijse.gdse.inventory.controller.InventoryItemController;
import edu.ijse.gdse.inventory.controller.PaymentController;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pahansith
 */
public class DashBoardForm extends javax.swing.JPanel {
    
    public DashBoardForm() {
        initComponents();
        setUnpaidInvoices();
        setReOrderClosingItems();
        setItemCount();
        setTotalValue();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        upperPanel = new javax.swing.JPanel();
        graphPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reOrderLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        graphPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        invoicesLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        graphPanel4 = new javax.swing.JPanel();
        stockValueLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        graphPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        totalProductLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(247, 246, 242));

        jPanel8.setBackground(new java.awt.Color(222, 98, 98));
        jPanel8.setMinimumSize(new java.awt.Dimension(1120, 10));
        jPanel8.setPreferredSize(new java.awt.Dimension(1120, 7));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel27.setBackground(new java.awt.Color(204, 204, 204));
        jLabel27.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("Dashboard");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 80));

        upperPanel.setBackground(new java.awt.Color(255, 255, 255));

        graphPanel1.setBackground(new java.awt.Color(42, 187, 155));
        graphPanel1.setMinimumSize(new java.awt.Dimension(276, 128));
        graphPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Anadi", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(81, 215, 209));
        jLabel1.setText("RE-ORDER");
        graphPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 86, 29));

        reOrderLabel.setFont(new java.awt.Font("Anadi", 1, 18)); // NOI18N
        reOrderLabel.setForeground(new java.awt.Color(255, 255, 253));
        reOrderLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reOrderLabel.setText("12");
        graphPanel1.add(reOrderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 30, 70, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setOpaque(true);
        graphPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 3));

        jLabel4.setFont(new java.awt.Font("Open Sans Semibold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(146, 228, 204));
        jLabel4.setText("re-order closing items");
        graphPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, -1));

        graphPanel3.setBackground(new java.awt.Color(142, 68, 173));
        graphPanel3.setMinimumSize(new java.awt.Dimension(276, 128));
        graphPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Anadi", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(203, 180, 213));
        jLabel14.setText("INVOICES");
        graphPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 86, 29));

        invoicesLabel.setFont(new java.awt.Font("Anadi", 1, 18)); // NOI18N
        invoicesLabel.setForeground(new java.awt.Color(233, 255, 255));
        invoicesLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        invoicesLabel.setText("8");
        graphPanel3.add(invoicesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 30, 60, 50));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setOpaque(true);
        graphPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 3));

        jLabel17.setFont(new java.awt.Font("Open Sans Semibold", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(203, 180, 213));
        jLabel17.setText("total upcoming payments");
        graphPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, -1));

        graphPanel4.setBackground(new java.awt.Color(255, 184, 73));
        graphPanel4.setMinimumSize(new java.awt.Dimension(276, 128));
        graphPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stockValueLabel.setFont(new java.awt.Font("Anadi", 1, 18)); // NOI18N
        stockValueLabel.setForeground(new java.awt.Color(233, 255, 255));
        stockValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stockValueLabel.setText("124500 LKR");
        graphPanel4.add(stockValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 30, 200, 50));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setOpaque(true);
        graphPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 3));

        jLabel21.setFont(new java.awt.Font("Open Sans Semibold", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(239, 253, 140));
        jLabel21.setText("total stock values");
        graphPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, -1));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Anadi", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(239, 253, 140));
        jLabel26.setText("VALUE");
        graphPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 86, 29));

        graphPanel5.setBackground(new java.awt.Color(65, 131, 215));
        graphPanel5.setMinimumSize(new java.awt.Dimension(276, 128));
        graphPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Anadi", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(157, 205, 234));
        jLabel22.setText("PRODUCTS");
        graphPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 86, 29));

        totalProductLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalProductLabel.setFont(new java.awt.Font("Anadi", 1, 18)); // NOI18N
        totalProductLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalProductLabel.setText("120");
        graphPanel5.add(totalProductLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 30, 70, 50));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setOpaque(true);
        graphPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 3));

        jLabel25.setFont(new java.awt.Font("Open Sans Semibold", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(144, 198, 237));
        jLabel25.setText("total inventry item");
        graphPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, -1));

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(graphPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(graphPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(graphPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(graphPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(graphPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(graphPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(graphPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(upperPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 1050, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventory-management.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 1000, 365));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphPanel1;
    private javax.swing.JPanel graphPanel3;
    private javax.swing.JPanel graphPanel4;
    private javax.swing.JPanel graphPanel5;
    private javax.swing.JLabel invoicesLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel reOrderLabel;
    private javax.swing.JLabel stockValueLabel;
    private javax.swing.JLabel totalProductLabel;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables

    private void setUnpaidInvoices() {
        try {
            int countOfUnpaidInvoices = PaymentController.countOfUnpaidInvoices();
            if(countOfUnpaidInvoices != -1){
                invoicesLabel.setText(Integer.toString(countOfUnpaidInvoices));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DashBoardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setReOrderClosingItems() {
        try {
            int countOfReOrderClosingItems = InventoryItemController.getCountOfReOrderClosingItems();
            if (countOfReOrderClosingItems != -1) {
                reOrderLabel.setText(Integer.toString(countOfReOrderClosingItems));
            }else{
                JOptionPane.showMessageDialog(DashBoardForm.this, "You Cannot Add these values", "Error Occured", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(DashBoardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setItemCount() {
        try {
            int inventoryCount = InventoryItemController.getInventoryCount();
            if (inventoryCount != -1) {
                totalProductLabel.setText(Integer.toString(inventoryCount));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DashBoardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setTotalValue() {
        try {
            double inventoryValue = InventoryItemController.getInventoryValue();
            if(inventoryValue != -1){
                DecimalFormat format = new DecimalFormat("#,###,###.##");
                String value = format.format(inventoryValue);
                stockValueLabel.setText(value+" LKR");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DashBoardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
}
