/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse.inventory.view.forms;

import edu.ijse.gdse.inventory.controller.PaymentTermController;
import edu.ijse.gdse.inventory.controller.TaxSchemeController;
import edu.ijse.gdse.inventory.controller.VendorController;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import edu.ijse.gdse.inventory.model.PaymentTerm;
import edu.ijse.gdse.inventory.model.TaxScheme;
import edu.ijse.gdse.inventory.model.Vendor;
import edu.ijse.gdse.inventory.other.ComboBoxHandler;
import edu.ijse.gdse.inventory.other.ComboSearch;
import edu.ijse.gdse.inventory.other.TextFieldHandler;
import edu.ijse.gdse.inventory.other.Validation;
import edu.ijse.gdse.inventory.view.main.HomeForm;
import edu.ijse.gdse.inventory.view.smallforms.NewTaxSchemeForm;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pahansith
 */
public class NewVendorForm extends javax.swing.JPanel {

    
    
    Vendor selectedVendor = null;
    JTextField[] nameField = null;
    JTextField[] addressField = null;
    private DefaultComboBoxModel termsComboModel;
    private DefaultComboBoxModel taxComboModel;
    PaymentTerm term = new PaymentTerm();
    private String nextVendorId;
    private String fullName;
    private String fullAddress;
    private ItemListener[] itemListeners;
    
     /**
     * Creates new form SaleItemForm
     */
    public NewVendorForm() {
        initComponents();
        setNextVendorId();
        setDefaultsToSearchPanel();
        setTermsCombo();
        taxComboRemoveListeners();
        setTaxCombo();
        taxComboSetListeners();
        setSearchCombo();
        setTextFieldReferencesToArray();
    }
    

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        vendorLabel = new javax.swing.JLabel();
        salesReportLabel = new javax.swing.JLabel();
        vendorItemLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        searchCombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        telephoneLabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        companyLabel = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        creditLimitLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        vendorHostPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mobileNumberField = new javax.swing.JTextField();
        webSiteField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        faxField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        fNameField = new javax.swing.JTextField();
        lNameField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        companyField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        vendorIdLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        addressField4 = new javax.swing.JTextField();
        addressField1 = new javax.swing.JTextField();
        addressField2 = new javax.swing.JTextField();
        addressField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        termsCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        taxCombo = new javax.swing.JComboBox<>();
        priceIncludeRadio = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        creditLimitField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        saveLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(247, 246, 242));

        jPanel8.setBackground(new java.awt.Color(43, 87, 154));
        jPanel8.setMinimumSize(new java.awt.Dimension(1120, 10));
        jPanel8.setPreferredSize(new java.awt.Dimension(1120, 7));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Vendor");

        jPanel3.setBackground(new java.awt.Color(247, 246, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        jPanel3.setLayout(null);

        vendorLabel.setBackground(new java.awt.Color(247, 246, 242));
        vendorLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vendorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vendorLabel.setText("Vendor List");
        vendorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        vendorLabel.setOpaque(true);
        vendorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vendorLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vendorLabelMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendorLabelMouseClicked(evt);
            }
        });
        jPanel3.add(vendorLabel);
        vendorLabel.setBounds(180, 0, 173, 68);

        salesReportLabel.setBackground(new java.awt.Color(247, 246, 242));
        salesReportLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salesReportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salesReportLabel.setText("Vendor Details");
        salesReportLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        salesReportLabel.setOpaque(true);
        salesReportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salesReportLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salesReportLabelMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesReportLabelMouseClicked(evt);
            }
        });
        jPanel3.add(salesReportLabel);
        salesReportLabel.setBounds(3, 0, 180, 68);

        vendorItemLabel.setBackground(new java.awt.Color(247, 246, 242));
        vendorItemLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vendorItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vendorItemLabel.setText("Vendor Items");
        vendorItemLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 227, 212)));
        vendorItemLabel.setOpaque(true);
        vendorItemLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vendorItemLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vendorItemLabelMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendorItemLabelMouseClicked(evt);
            }
        });
        jPanel3.add(vendorItemLabel);
        vendorItemLabel.setBounds(350, 0, 170, 68);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 90));

        jPanel11.setBackground(new java.awt.Color(43, 87, 154));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 229, 208)));
        jPanel11.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(43, 87, 154));
        jPanel12.setLayout(null);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Search");
        jPanel12.add(jLabel22);
        jLabel22.setBounds(0, 30, 49, 37);

        searchCombo.setEditable(true);
        searchCombo.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        searchCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchComboItemStateChanged(evt);
            }
        });
        searchCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchComboActionPerformed(evt);
            }
        });
        searchCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchComboKeyTyped(evt);
            }
        });
        jPanel12.add(searchCombo);
        searchCombo.setBounds(0, 60, 240, 28);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setOpaque(true);
        jPanel12.add(jLabel13);
        jLabel13.setBounds(0, 130, 238, 3);

        jPanel11.add(jPanel12);
        jPanel12.setBounds(10, 20, 240, 150);

        jPanel13.setBackground(new java.awt.Color(43, 87, 154));
        jPanel13.setLayout(null);

        idLabel.setBackground(new java.awt.Color(255, 255, 255));
        idLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.add(idLabel);
        idLabel.setBounds(110, 20, 130, 37);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("VID -");
        jPanel13.add(jLabel25);
        jLabel25.setBounds(10, 20, 60, 37);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Name -");
        jPanel13.add(jLabel26);
        jLabel26.setBounds(10, 70, 60, 37);

        nameLabel.setBackground(new java.awt.Color(255, 255, 255));
        nameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.add(nameLabel);
        nameLabel.setBounds(110, 70, 130, 37);

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Telephone -");
        jPanel13.add(jLabel28);
        jLabel28.setBounds(10, 120, 90, 37);

        telephoneLabel.setBackground(new java.awt.Color(255, 255, 255));
        telephoneLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        telephoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.add(telephoneLabel);
        telephoneLabel.setBounds(110, 120, 130, 37);

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Company -");
        jPanel13.add(jLabel30);
        jLabel30.setBounds(10, 170, 90, 37);

        companyLabel.setBackground(new java.awt.Color(255, 255, 255));
        companyLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        companyLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.add(companyLabel);
        companyLabel.setBounds(110, 170, 130, 37);

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Credit Limit -");
        jPanel13.add(jLabel32);
        jLabel32.setBounds(10, 220, 91, 37);

        creditLimitLabel.setBackground(new java.awt.Color(255, 255, 255));
        creditLimitLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        creditLimitLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.add(creditLimitLabel);
        creditLimitLabel.setBounds(110, 220, 130, 37);

        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel13.add(deleteButton);
        deleteButton.setBounds(140, 300, 90, 25);

        editButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel13.add(editButton);
        editButton.setBounds(10, 300, 90, 25);

        jPanel11.add(jPanel13);
        jPanel13.setBounds(10, 160, 240, 370);

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 260, 540));

        vendorHostPanel.setBackground(new java.awt.Color(255, 255, 255));
        vendorHostPanel.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(43, 87, 154), 1, true));
        jPanel2.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  Contact");
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 490, 30);

        mobileNumberField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mobileNumberField.setForeground(new java.awt.Color(102, 102, 102));
        mobileNumberField.setBorder(fNameField.getBorder());
        mobileNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileNumberFieldKeyTyped(evt);
            }
        });
        jPanel2.add(mobileNumberField);
        mobileNumberField.setBounds(70, 120, 140, 30);

        webSiteField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        webSiteField.setForeground(new java.awt.Color(102, 102, 102));
        webSiteField.setBorder(fNameField.getBorder());
        jPanel2.add(webSiteField);
        webSiteField.setBounds(310, 70, 170, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("WebSite");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(220, 70, 71, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Mobile");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 120, 60, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Fax");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 172, 40, 30);

        faxField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        faxField.setForeground(new java.awt.Color(102, 102, 102));
        faxField.setBorder(fNameField.getBorder());
        faxField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                faxFieldKeyTyped(evt);
            }
        });
        jPanel2.add(faxField);
        faxField.setBounds(70, 170, 140, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Phone");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 70, 54, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Email");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(220, 120, 71, 30);

        emailField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailField.setForeground(new java.awt.Color(102, 102, 102));
        emailField.setBorder(fNameField.getBorder());
        jPanel2.add(emailField);
        emailField.setBounds(310, 120, 170, 30);

        phoneNumberField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phoneNumberField.setForeground(new java.awt.Color(102, 102, 102));
        phoneNumberField.setBorder(fNameField.getBorder());
        phoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberFieldActionPerformed(evt);
            }
        });
        phoneNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneNumberFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberFieldKeyTyped(evt);
            }
        });
        jPanel2.add(phoneNumberField);
        phoneNumberField.setBounds(70, 70, 140, 30);

        jLabel27.setText("*");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(60, 80, 20, 20);

        vendorHostPanel.add(jPanel2);
        jPanel2.setBounds(10, 290, 490, 250);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(43, 87, 154), 1, true));
        jPanel6.setLayout(null);

        fNameField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fNameField.setForeground(new java.awt.Color(193, 186, 171));
        fNameField.setText(" First Name");
        fNameField.setBorder(phoneNumberField.getBorder());
        fNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fNameFieldFocusGained(evt);
            }
        });
        fNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fNameFieldKeyTyped(evt);
            }
        });
        jPanel6.add(fNameField);
        fNameField.setBounds(90, 90, 150, 30);

        lNameField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lNameField.setForeground(new java.awt.Color(193, 186, 171));
        lNameField.setText(" Last Name");
        lNameField.setBorder(fNameField.getBorder());
        lNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lNameFieldFocusGained(evt);
            }
        });
        lNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lNameFieldKeyTyped(evt);
            }
        });
        jPanel6.add(lNameField);
        lNameField.setBounds(250, 90, 168, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Name");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(10, 90, 54, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Address");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(11, 138, 73, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Company");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(10, 220, 73, 40);

        companyField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        companyField.setForeground(new java.awt.Color(102, 102, 102));
        companyField.setBorder(fNameField.getBorder());
        companyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyFieldActionPerformed(evt);
            }
        });
        jPanel6.add(companyField);
        companyField.setBounds(90, 230, 141, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Vendor ID");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(10, 50, 70, 30);

        vendorIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vendorIdLabel.setForeground(new java.awt.Color(102, 102, 102));
        jPanel6.add(vendorIdLabel);
        vendorIdLabel.setBounds(90, 50, 64, 30);

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("  Basic");
        jLabel21.setOpaque(true);
        jPanel6.add(jLabel21);
        jLabel21.setBounds(0, 0, 490, 30);

        addressField4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addressField4.setForeground(new java.awt.Color(193, 186, 171));
        addressField4.setText(" Steet 4");
        addressField4.setBorder(fNameField.getBorder());
        addressField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressField4FocusGained(evt);
            }
        });
        jPanel6.add(addressField4);
        addressField4.setBounds(290, 180, 190, 30);

        addressField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addressField1.setForeground(new java.awt.Color(193, 186, 171));
        addressField1.setText(" Steet 1");
        addressField1.setBorder(fNameField.getBorder());
        addressField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressField1FocusGained(evt);
            }
        });
        addressField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressField1KeyTyped(evt);
            }
        });
        jPanel6.add(addressField1);
        addressField1.setBounds(90, 140, 190, 30);

        addressField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addressField2.setForeground(new java.awt.Color(193, 186, 171));
        addressField2.setText(" Steet 2");
        addressField2.setBorder(fNameField.getBorder());
        addressField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressField2FocusGained(evt);
            }
        });
        jPanel6.add(addressField2);
        addressField2.setBounds(290, 140, 190, 30);

        addressField3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addressField3.setForeground(new java.awt.Color(193, 186, 171));
        addressField3.setText(" Steet 3");
        addressField3.setBorder(fNameField.getBorder());
        addressField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressField3FocusGained(evt);
            }
        });
        jPanel6.add(addressField3);
        addressField3.setBounds(90, 180, 190, 30);

        jLabel7.setText("*");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(70, 150, 20, 14);

        jLabel10.setText("*");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(60, 100, 20, 14);

        vendorHostPanel.add(jPanel6);
        jPanel6.setBounds(10, 10, 490, 270);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(43, 87, 154), 1, true));
        jPanel5.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Payment Terms");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 30, 120, 40);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  Payment Info");
        jLabel5.setOpaque(true);
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, 0, 330, 30);

        termsCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        termsCombo.setForeground(new java.awt.Color(102, 102, 102));
        termsCombo.setBorder(null);
        termsCombo.setOpaque(false);
        termsCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                termsComboItemStateChanged(evt);
            }
        });
        jPanel5.add(termsCombo);
        termsCombo.setBounds(150, 40, 170, 25);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Price Include Tax");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(10, 220, 130, 50);

        taxCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        taxCombo.setForeground(new java.awt.Color(102, 102, 102));
        taxCombo.setBorder(null);
        taxCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                taxComboItemStateChanged(evt);
            }
        });
        taxCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxComboActionPerformed(evt);
            }
        });
        jPanel5.add(taxCombo);
        taxCombo.setBounds(150, 170, 170, 25);
        jPanel5.add(priceIncludeRadio);
        priceIncludeRadio.setBounds(150, 230, 21, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Taxing Scheme");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 160, 110, 40);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Credit Limit");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(10, 90, 80, 40);

        creditLimitField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        creditLimitField.setForeground(new java.awt.Color(102, 102, 102));
        creditLimitField.setBorder(fNameField.getBorder());
        creditLimitField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                creditLimitFieldKeyTyped(evt);
            }
        });
        jPanel5.add(creditLimitField);
        creditLimitField.setBounds(150, 100, 140, 25);

        jLabel29.setText("*");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(120, 40, 20, 30);

        jLabel31.setText("*");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(120, 170, 20, 30);

        jLabel33.setText("*");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(100, 100, 20, 30);

        vendorHostPanel.add(jPanel5);
        jPanel5.setBounds(510, 10, 330, 270);

        jPanel9.setBackground(new java.awt.Color(43, 87, 154));

        saveLabel.setBackground(new java.awt.Color(43, 87, 154));
        saveLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        saveLabel.setForeground(new java.awt.Color(255, 255, 255));
        saveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveLabel.setText("Save vendor");
        saveLabel.setOpaque(true);
        saveLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(saveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        vendorHostPanel.add(jPanel9);
        jPanel9.setBounds(520, 480, 170, 50);

        jLabel3.setBackground(new java.awt.Color(68, 106, 129));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cancel");
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        vendorHostPanel.add(jPanel10);
        jPanel10.setBounds(700, 480, 120, 50);

        jLabel24.setText("*");
        vendorHostPanel.add(jLabel24);
        jLabel24.setBounds(70, 150, 20, 14);

        add(vendorHostPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1120, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void searchComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchComboItemStateChanged
        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (searchCombo.getSelectedItem() != null) {
                try {
                    String selectedItem = (String) searchCombo.getSelectedItem();
                    String[] split = selectedItem.split("-"); //Split from the '-' mark and get VID
                    String vid = null;
                    try{vid = split[1].trim();}catch(ArrayIndexOutOfBoundsException e){}
                    selectedVendor = VendorController.searchVendor(vid);
                    
                    if (selectedVendor != null) {
                        idLabel.setText(selectedVendor.getVendorId());
                        nameLabel.setText(selectedVendor.getName());
                        telephoneLabel.setText(Integer.toString(selectedVendor.getTelephoneNumber()));
                        companyLabel.setText(selectedVendor.getCompany());
                        creditLimitLabel.setText(Double.toString(selectedVendor.getCreditLimit()));
                    }
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_searchComboItemStateChanged

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (selectedVendor != null) {
            try {
                boolean isDeleted = VendorController.deleteVendor(selectedVendor.getVendorId());
                setSearchCombo();
                setDefaultsToSearchPanel();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (selectedVendor != null) {
            focusGainTextFields();
            
            vendorIdLabel.setText(selectedVendor.getVendorId());
            String[] name = selectedVendor.getName().split(" ");
            String[] address = selectedVendor.getAddress().split(",");
            
            if (name != null) {
                for (int i = 0; i < name.length; i++) {
                    nameField[i].setText(name[i]);
                }
            }
            
            if (address != null) {
                for (int i = 0; i < address.length; i++) {
                    addressField[i].setText(address[i]);
                }
            }
            phoneNumberField.setText(Integer.toString(selectedVendor.getTelephoneNumber()));

            for (int i = 2; i < termsCombo.getItemCount(); i++) {
                PaymentTerm term = (PaymentTerm) termsComboModel.getElementAt(i);
                if(term.getTermId().equals(selectedVendor.getTermId())){
                    termsCombo.setSelectedIndex(i);
                }
            }
            
            for (int i = 2; i < taxCombo.getItemCount(); i++) {
                TaxScheme tax = (TaxScheme) taxComboModel.getElementAt(i);
                if (tax.getTaxId().equals(selectedVendor.getTaxId())) {
                    taxCombo.setSelectedIndex(i);
                }
            }
            
            creditLimitField.setText(Double.toString(selectedVendor.getCreditLimit()));
            //Possbily null values
            if (selectedVendor.getCompany() != null) {
                companyField.setText(selectedVendor.getCompany());
            }
            if (selectedVendor.getWebSite() != null) {
                webSiteField.setText(selectedVendor.getWebSite());
            }
            if (selectedVendor.getEmailAddress() != null) {
                emailField.setText(selectedVendor.getEmailAddress());
            }
            if (selectedVendor.getMobileNumber() != 0) {
                mobileNumberField.setText(Integer.toString(selectedVendor.getMobileNumber()));
            }
            if (selectedVendor.getFax() != 0) {
                faxField.setText(Integer.toString(selectedVendor.getFax()));
            }

        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void searchComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchComboActionPerformed
        
    }//GEN-LAST:event_searchComboActionPerformed

    private void searchComboKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchComboKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_searchComboKeyTyped

    private void vendorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorLabelMouseClicked
       
    }//GEN-LAST:event_vendorLabelMouseClicked

    private void salesReportLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesReportLabelMouseEntered
        salesReportLabel.setBackground(new Color(247,246,209));
    }//GEN-LAST:event_salesReportLabelMouseEntered

    private void salesReportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesReportLabelMouseClicked
       
    }//GEN-LAST:event_salesReportLabelMouseClicked

    private void vendorItemLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorItemLabelMouseClicked
        
    }//GEN-LAST:event_vendorItemLabelMouseClicked

    private void vendorLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorLabelMouseEntered
        vendorLabel.setBackground(new Color(247,246,209));
    }//GEN-LAST:event_vendorLabelMouseEntered

    private void vendorItemLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorItemLabelMouseEntered
        vendorItemLabel.setBackground(new Color(247,246,209));
    }//GEN-LAST:event_vendorItemLabelMouseEntered

    private void salesReportLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesReportLabelMouseExited
        salesReportLabel.setBackground(new Color(247,246,242));
    }//GEN-LAST:event_salesReportLabelMouseExited

    private void vendorLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorLabelMouseExited
        vendorLabel.setBackground(new Color(247,246,242));
    }//GEN-LAST:event_vendorLabelMouseExited

    private void vendorItemLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorItemLabelMouseExited
        vendorItemLabel.setBackground(new Color(247,246,242));
    }//GEN-LAST:event_vendorItemLabelMouseExited

    private void saveLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveLabelMouseClicked
        if (isAllNotNullFieldsCompleted() && isAllComboBoxesSelected()) {
            if (vendorIdLabel.getText().equals(nextVendorId)) {
                saveVendorDetails(getSelectedVendorDetails());
                HomeForm.setVendorForm();
            } else {
                updateVendorDetails(getSelectedVendorDetails());
            }
        }
    }//GEN-LAST:event_saveLabelMouseClicked

    private void creditLimitFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditLimitFieldKeyTyped
        Validation.validateOnlyForNumbers(evt);
    }//GEN-LAST:event_creditLimitFieldKeyTyped

    private void taxComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxComboActionPerformed

    }//GEN-LAST:event_taxComboActionPerformed

    private void taxComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_taxComboItemStateChanged
        if (taxCombo.getSelectedIndex() == 0) {
            NewTaxSchemeForm form = new NewTaxSchemeForm(this);
            form.setVisible(true);
        }
    }//GEN-LAST:event_taxComboItemStateChanged

    private void termsComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_termsComboItemStateChanged

    }//GEN-LAST:event_termsComboItemStateChanged

    private void addressField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressField3FocusGained
        TextFieldHandler.focusGained(addressField3);
    }//GEN-LAST:event_addressField3FocusGained

    private void addressField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressField2FocusGained
        TextFieldHandler.focusGained(addressField2);
    }//GEN-LAST:event_addressField2FocusGained

    private void addressField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressField1KeyTyped

    }//GEN-LAST:event_addressField1KeyTyped

    private void addressField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressField1FocusGained
        TextFieldHandler.focusGained(addressField1);
    }//GEN-LAST:event_addressField1FocusGained

    private void addressField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressField4FocusGained
        TextFieldHandler.focusGained(addressField4);
    }//GEN-LAST:event_addressField4FocusGained

    private void companyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyFieldActionPerformed

    private void lNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNameFieldKeyTyped
        Validation.validateOnlyForCharacters(evt);
    }//GEN-LAST:event_lNameFieldKeyTyped

    private void lNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lNameFieldFocusGained
        TextFieldHandler.focusGained(lNameField);
    }//GEN-LAST:event_lNameFieldFocusGained

    private void fNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameFieldKeyTyped
        Validation.validateOnlyForCharacters(evt);
    }//GEN-LAST:event_fNameFieldKeyTyped

    private void fNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNameFieldFocusGained
        TextFieldHandler.focusGained(fNameField);
    }//GEN-LAST:event_fNameFieldFocusGained

    private void phoneNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberFieldKeyTyped
        Validation.validateOnlyForNumbers(evt);
    }//GEN-LAST:event_phoneNumberFieldKeyTyped

    private void phoneNumberFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberFieldKeyPressed
        //Validate.validateTextFieldForNumber(phoneNumberField);
        //Validate.validateContactNumber(phoneNumberField);
    }//GEN-LAST:event_phoneNumberFieldKeyPressed

    private void phoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberFieldActionPerformed

    private void faxFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_faxFieldKeyTyped
        Validation.validateOnlyForNumbers(evt);
    }//GEN-LAST:event_faxFieldKeyTyped

    private void mobileNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileNumberFieldKeyTyped
        Validation.validateOnlyForNumbers(evt);
    }//GEN-LAST:event_mobileNumberFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField1;
    private javax.swing.JTextField addressField2;
    private javax.swing.JTextField addressField3;
    private javax.swing.JTextField addressField4;
    private javax.swing.JTextField companyField;
    private javax.swing.JLabel companyLabel;
    private javax.swing.JTextField creditLimitField;
    private javax.swing.JLabel creditLimitLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fNameField;
    private javax.swing.JTextField faxField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField lNameField;
    private javax.swing.JTextField mobileNumberField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JCheckBox priceIncludeRadio;
    private javax.swing.JLabel salesReportLabel;
    private javax.swing.JLabel saveLabel;
    private javax.swing.JComboBox<String> searchCombo;
    private javax.swing.JComboBox<String> taxCombo;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JComboBox<String> termsCombo;
    private javax.swing.JPanel vendorHostPanel;
    private javax.swing.JLabel vendorIdLabel;
    private javax.swing.JLabel vendorItemLabel;
    private javax.swing.JLabel vendorLabel;
    private javax.swing.JTextField webSiteField;
    // End of variables declaration//GEN-END:variables

    private void setNextVendorId() {
        try {
            nextVendorId = VendorController.getNextVendorId();
            vendorIdLabel.setText(nextVendorId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void setTermsCombo() {        
        termsCombo.addItem("-New Term");
        termsCombo.setSelectedIndex(-1);
        termsComboModel = (DefaultComboBoxModel) termsCombo.getModel();
        try {
            ArrayList<PaymentTerm> allPayementTerms = PaymentTermController.getAllPayementTerms();
            for (PaymentTerm term : allPayementTerms) {
                termsComboModel.addElement(term);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setTaxCombo() {
        taxCombo.removeAllItems();
        taxCombo.addItem("-New Scheme");
        taxComboModel = (DefaultComboBoxModel) taxCombo.getModel();
        try {
            ArrayList<TaxScheme> allTaxScehemes = TaxSchemeController.getAllTaxScehemes();
            for (TaxScheme scheme : allTaxScehemes) {
                taxComboModel.addElement(scheme);
            }
            taxCombo.setSelectedIndex(-1);
        } catch (SQLException ex) {
            Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //Set Vendor Id and Name to the SearchCombo Box
    private void setSearchCombo() {
        searchCombo.removeAllItems();
        try {
            ItemListener[] itemListeners = searchCombo.getItemListeners();
            searchCombo.removeItemListener(itemListeners[0]);
            ArrayList<String> vendorNames = VendorController.getVendorNames();
            for (String name : vendorNames) {
                searchCombo.addItem(name);
            }
            searchCombo.setSelectedItem(null);
            searchCombo.addItemListener(itemListeners[0]);
            
            
            //pass combo box object to ComboSearch class
            new ComboSearch().setSearchableCombo(searchCombo, true, "No Result Found");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void focusGainTextFields() {
        TextFieldHandler setTextFields = new TextFieldHandler();
        TextFieldHandler.focusGained(fNameField);
        TextFieldHandler.focusGained(lNameField);
        TextFieldHandler.focusGained(addressField1);
        TextFieldHandler.focusGained(addressField2);
        TextFieldHandler.focusGained(addressField3);
        TextFieldHandler.focusGained(addressField4);
    }

    
    private void setTextFieldReferencesToArray() {
        nameField = new JTextField[2];
        nameField[0] = fNameField;
        nameField[1] = lNameField;
        
        addressField = new JTextField[4];
        addressField[0] = addressField1;
        addressField[1] = addressField2;
        addressField[2] = addressField3;
        addressField[3] = addressField4;
    }

    private void updateVendorDetails(Vendor selectedVendorDetails) {
        try {
            boolean isUpdated = VendorController.updateVendor(selectedVendorDetails);
            if(isUpdated){
                JOptionPane.showMessageDialog(NewVendorForm.this, "Customer Updated Succesfull", "Customer Updated", JOptionPane.INFORMATION_MESSAGE);
            }else{
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void saveVendorDetails(Vendor selectedVendorDetails) {
        try {
            boolean isAdded = VendorController.addNewVendor(selectedVendorDetails);
            if(isAdded){
                JOptionPane.showMessageDialog(NewVendorForm.this, "Customer Added Succesfull", "Customer Added", JOptionPane.INFORMATION_MESSAGE);
                
                JPanel formsPanelInstance = HomeForm.getFormsPanelInstance();
                formsPanelInstance.removeAll();
                formsPanelInstance.add(new NewVendorForm());
                formsPanelInstance.repaint();
                formsPanelInstance.revalidate();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewVendorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Vendor getSelectedVendorDetails() {
        //Get Data for create Vendor Object
        //Not Null fields
        String vendorId = vendorIdLabel.getText();
        String fName = fNameField.getText();
        String lName = lNameField.getText();
        String address1 = addressField1.getText();
        String address2 = addressField2.getText();
        String address3 = addressField3.getText();
        String address4 = addressField4.getText();
        PaymentTerm paymentTerm = (PaymentTerm) termsCombo.getSelectedItem();
        TaxScheme scheme = (TaxScheme) taxCombo.getSelectedItem();

        fullName = fName + " " + lName;
        fullAddress = address1 + "," + address2 + "," + address3 + "," + address4;
        int phoneNumber = Integer.parseInt(phoneNumberField.getText());
        String termId = paymentTerm.getTermId();
        double creditLimit = Double.parseDouble(creditLimitField.getText());
        String taxId = scheme.getTaxId();
        boolean isSelected = priceIncludeRadio.isSelected();
        
        //Null Accepted Fields
        String company = TextFieldHandler.textCheck(companyField.getText());
        String webSite = TextFieldHandler.textCheck(webSiteField.getText());
        int mobileNumber =TextFieldHandler.numberCheck(mobileNumberField.getText());
        String email = TextFieldHandler.textCheck(emailField.getText());
        int fax = TextFieldHandler.numberCheck(faxField.getText());
        
        
        //Create Vendor Object
        Vendor vendor = new Vendor();
        vendor.setVendorId(vendorId);
        vendor.setName(fullName);
        vendor.setAddress(fullAddress);
        vendor.setCompany(company);
        vendor.setTelephoneNumber(phoneNumber);
        vendor.setWebSite(webSite);
        vendor.setMobileNumber(mobileNumber);
        vendor.setEmailAddress(email);
        vendor.setFax(fax);
        vendor.setTermId(termId);
        vendor.setCreditLimit(creditLimit);
        vendor.setTaxStatus(isSelected);
        vendor.setTaxId(taxId);
        
        return vendor;
    }

    private void setDefaultsToSearchPanel() {
        idLabel.setText(null);
        nameLabel.setText(null);
        telephoneLabel.setText(null);
        companyLabel.setText(null);
        creditLimitLabel.setText(null);
    }

    private boolean isAllNotNullFieldsCompleted() {
        return TextFieldHandler.isAllTextFieldsFilled(fNameField,addressField1,addressField2,phoneNumberField,creditLimitField);
    }

    private boolean isAllComboBoxesSelected() {
        return ComboBoxHandler.isAllComboBoxesSelected(termsCombo,taxCombo);
    }

    private void taxComboRemoveListeners() {
        itemListeners = taxCombo.getItemListeners();
        taxCombo.removeItemListener(itemListeners[0]);
    }

    private void taxComboSetListeners() {
        taxCombo.addItemListener(itemListeners[0]);
        itemListeners = null;
    }

    public void loadTaxCombo() {
        taxComboRemoveListeners();
        setTaxCombo();
        taxComboSetListeners();
    }
    
}
