/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse.inventory.view.forms;

import edu.ijse.gdse.inventory.controller.InventoryItemController;
import edu.ijse.gdse.inventory.controller.SaleController;
import edu.ijse.gdse.inventory.controller.SaleItemController;
import java.awt.Color;
import java.awt.HeadlessException;
import edu.ijse.gdse.inventory.view.smallforms.PaymentForm;
import edu.ijse.gdse.inventory.view.smallforms.SelectedItemPanel;
import edu.ijse.gdse.inventory.model.Sale;
import edu.ijse.gdse.inventory.model.SaleItem;
import edu.ijse.gdse.inventory.model.helper.SelectedItem;
import edu.ijse.gdse.inventory.model.helper.SellInventoryItem;
import edu.ijse.gdse.inventory.other.IDGenerator;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import edu.ijse.gdse.inventory.model.helper.DeleteSaleItem;
import edu.ijse.gdse.inventory.view.main.HomeForm;

/**
 *
 * @author Pahansith
 */
public class SaleItemForm extends javax.swing.JPanel {

    
    private static int x = 0;
    private static int y = 0;
    private static int count = 0;
    private static int subTotal = 0;
    private static double grossTotal;
    private static double totalDiscount;
    private static double tax;
    private String salesId;
    private double subDiscount = 0;
    private static ArrayList<SaleItem> saleItemList = new ArrayList<>();
    private static int counter = 0;
    
    //Runs when customer clicked selectedItemPanel by mouse
    public static void setSelectItemDetails(SelectedItem item, SelectedItemPanel panel) {
        descriptionLabel.setText(item.getDescription());
        priceLabel.setText(Double.toString(item.getSoldPrice()));
        qtyText.setText(Integer.toString(item.getSoldQty()));
        discountLabel.setText(Double.toString(item.getDiscount()));
        String itemCode = item.getItemCode();
        DeleteSaleItem.setItemCode(itemCode);
        DeleteSaleItem.setItemPanel(panel);
    }
    
    
    //Runs after payment made by customer and clicked Print bill button on Payment form
    public static void doTransaction(boolean b, double receivedCash) {
        try {
            
            //get details for sale object
            double balance = receivedCash - grossTotal;
            String billNumber = billNumberLabel.getText();
            String nic = salesPersonIdLabel.getText();
            String date = dateLabel.getText();
            tax = Double.parseDouble(taxLabel.getText());
            
            //Creation of Sale Object
            Sale sale = new Sale(billNumber, nic, date, totalDiscount, grossTotal, receivedCash, balance, tax);
            
            //Runs when transaction process happen
            boolean isTransactionDone = SaleController.newSale(sale, saleItemList);
            
            if (isTransactionDone) {
                
                //After the Transaction has been made
                SaleItemForm saleItemForm = new SaleItemForm();
                
            } else {
                //If Transaction Not Happens
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SaleItemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SaleItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form SaleItemForm
     */
    public SaleItemForm() {
        initComponents();
        setInvoieNumber();
        setBillDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        billNumberLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        salesPersonLabel = new javax.swing.JLabel();
        salesPersonIdLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        setDiscountLabel = new javax.swing.JLabel();
        discountField = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        subTotalLabel = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        payPanel = new javax.swing.JPanel();
        paymentLabel = new javax.swing.JLabel();
        doPaymentLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qtyText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        addItemLabel = new javax.swing.JLabel();
        deleteLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        orderItemsPanel = new javax.swing.JPanel();
        searchText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Bill Number");

        billNumberLabel.setForeground(new java.awt.Color(100, 180, 199));
        billNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Date");

        dateLabel.setForeground(new java.awt.Color(100, 180, 199));
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        salesPersonLabel.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        salesPersonLabel.setForeground(new java.awt.Color(102, 102, 102));
        salesPersonLabel.setText("Sales Person");

        salesPersonIdLabel.setForeground(new java.awt.Color(100, 180, 199));
        salesPersonIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salesPersonIdLabel.setText("920601375V");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesPersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salesPersonIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(billNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(billNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salesPersonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salesPersonIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 340, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(null);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        setDiscountLabel.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        setDiscountLabel.setForeground(new java.awt.Color(0, 102, 255));
        setDiscountLabel.setText("  Add Discount");
        setDiscountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setDiscountLabelMouseClicked(evt);
            }
        });

        discountField.setEditable(false);
        discountField.setBackground(new java.awt.Color(255, 255, 255));
        discountField.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        discountField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        discountField.setBorder(null);
        discountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                discountFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(setDiscountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(setDiscountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
            .addComponent(discountField)
        );

        jPanel2.add(jPanel14);
        jPanel14.setBounds(0, 0, 340, 50);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jLabel14.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("  Sub-Total");

        subTotalLabel.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        subTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTotalLabel.setText("0.0");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(subTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
            .addComponent(subTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel15);
        jPanel15.setBounds(0, 50, 340, 50);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        jLabel13.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("  Tax");

        taxLabel.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        taxLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taxLabel.setText("0.0");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(taxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
            .addComponent(taxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel18);
        jPanel18.setBounds(0, 100, 340, 50);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jLabel18.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("  Total");

        totalLabel.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalLabel.setText("0.0");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel19);
        jPanel19.setBounds(0, 150, 340, 50);

        payPanel.setBackground(new java.awt.Color(0, 138, 232));

        paymentLabel.setFont(new java.awt.Font("Open Sans", 1, 22)); // NOI18N
        paymentLabel.setForeground(new java.awt.Color(255, 255, 255));
        paymentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentLabel.setText("0.0");

        doPaymentLabel.setBackground(new java.awt.Color(255, 255, 255));
        doPaymentLabel.setFont(new java.awt.Font("Open Sans", 1, 22)); // NOI18N
        doPaymentLabel.setForeground(new java.awt.Color(255, 255, 255));
        doPaymentLabel.setText("  Pay");
        doPaymentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doPaymentLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout payPanelLayout = new javax.swing.GroupLayout(payPanel);
        payPanel.setLayout(payPanelLayout);
        payPanelLayout.setHorizontalGroup(
            payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payPanelLayout.createSequentialGroup()
                .addComponent(doPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        payPanelLayout.setVerticalGroup(
            payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(payPanel);
        payPanel.setBounds(0, 200, 340, 60);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 340, 260));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        jPanel5.setLayout(null);

        descriptionLabel.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(descriptionLabel);
        descriptionLabel.setBounds(0, 20, 340, 30);

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(193, 186, 171));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Item");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(0, 0, 340, 20);

        jPanel6.add(jPanel5);
        jPanel5.setBounds(0, 0, 340, 52);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        jPanel3.setLayout(null);

        jSeparator1.setForeground(new java.awt.Color(204, 204, 250));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(101, 1, 10, 60);

        jSeparator2.setForeground(new java.awt.Color(204, 204, 250));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(240, 0, 10, 60);

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(193, 186, 171));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Unit Price");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 100, 20);

        priceLabel.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(0, 153, 255));
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("0.0");
        jPanel3.add(priceLabel);
        priceLabel.setBounds(10, 20, 80, 30);

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(193, 186, 171));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quantity");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(100, 0, 140, 20);

        qtyText.setFont(new java.awt.Font("Open Sans Extrabold", 0, 24)); // NOI18N
        qtyText.setForeground(new java.awt.Color(0, 153, 255));
        qtyText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyText.setText("1");
        qtyText.setBorder(null);
        qtyText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qtyTextFocusGained(evt);
            }
        });
        qtyText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                qtyTextMousePressed(evt);
            }
        });
        qtyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTextActionPerformed(evt);
            }
        });
        qtyText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyTextKeyPressed(evt);
            }
        });
        jPanel3.add(qtyText);
        qtyText.setBounds(110, 20, 120, 30);

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(193, 186, 171));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Discount");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(240, 0, 100, 20);

        discountLabel.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        discountLabel.setForeground(new java.awt.Color(0, 153, 255));
        discountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        discountLabel.setText("0.0");
        jPanel3.add(discountLabel);
        discountLabel.setBounds(250, 20, 80, 30);

        jPanel6.add(jPanel3);
        jPanel3.setBounds(0, 50, 340, 60);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        addItemLabel.setBackground(new java.awt.Color(204, 204, 255));
        addItemLabel.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        addItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addItemLabel.setText("Add");
        addItemLabel.setOpaque(true);
        addItemLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addItemLabelMouseClicked(evt);
            }
        });

        deleteLabel.setBackground(new java.awt.Color(255, 204, 204));
        deleteLabel.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        deleteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteLabel.setText("Delete");
        deleteLabel.setOpaque(true);
        deleteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(addItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addItemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(deleteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel4);
        jPanel4.setBounds(0, 120, 340, 40);

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 340, 170));

        jPanel7.setBackground(new java.awt.Color(247, 246, 242));

        jPanel8.setBackground(new java.awt.Color(99, 111, 221));
        jPanel8.setMinimumSize(new java.awt.Dimension(1120, 10));
        jPanel8.setPreferredSize(new java.awt.Dimension(1120, 7));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Sell Items");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(150, 150, 150))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 80));

        orderItemsPanel.setBackground(new java.awt.Color(255, 255, 255));
        orderItemsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        orderItemsPanel.setPreferredSize(new java.awt.Dimension(680, 380));
        orderItemsPanel.setLayout(null);
        add(orderItemsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 670, 400));

        searchText.setColumns(10);
        searchText.setForeground(new java.awt.Color(100, 180, 199));
        searchText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 180, 199), 1, true));
        searchText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFocusLost(evt);
            }
        });
        searchText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchTextMousePressed(evt);
            }
        });
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });
        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTextKeyPressed(evt);
            }
        });
        add(searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 440, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed

    }//GEN-LAST:event_searchTextActionPerformed

    private void searchTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTextMousePressed
        setDefaults();
    }//GEN-LAST:event_searchTextMousePressed

    private void addItemLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemLabelMouseClicked
        addSaleItemPanel();
        
    }//GEN-LAST:event_addItemLabelMouseClicked

    private void addSaleItemPanel() throws HeadlessException, NumberFormatException {
        //Add Selected Items to Order Items Panel
        try {
            if (!descriptionLabel.getText().isEmpty()) {
                SelectedItemPanel selectedItem = null;
                String itemCode = searchText.getText();
                String description = descriptionLabel.getText();
                double soldPrice = Double.parseDouble(priceLabel.getText()) - Double.parseDouble(discountLabel.getText());
                int soldQty = Integer.parseInt(qtyText.getText());
                double discountOfItem = Double.parseDouble(discountLabel.getText());
                
                salesId = getSaleId(salesId); //Generate Sales ID(This Should Increment by one for every single item)
                
                if (counter == 15) {
                    orderItemsPanel.setSize(orderItemsPanel.getWidth(), orderItemsPanel.getHeight() + 120);
                    orderItemsPanel.repaint();
                    System.out.println("asjd");
                }
                //This Logic is used for add the small panel to Order Items Panel
                if (x != 0) {
                    if (count < 5) {
                        x += (120 + 10);
                    } else {
                        x = 10;
                        y += (120 + 10);
                        count = 0;
                    }
                } else {
                    x = 10;
                    y = 10;
                    
                }
                
                selectedItem = new SelectedItemPanel(itemCode, description, soldPrice, soldQty, discountOfItem, x, y);
                orderItemsPanel.add(selectedItem);
                orderItemsPanel.repaint();
                
                String billNumber = billNumberLabel.getText();
                double amount = soldPrice * soldQty;
                double labeledPrice = Double.parseDouble(priceLabel.getText());
                
                //Generate sale item objects for customer selected items & add them to saleItemList static Array List
                saleItemList.add(new SaleItem(salesId, itemCode, billNumber, amount, labeledPrice, soldPrice, soldQty, discountOfItem));
                setTotal();
                setDefaults();
                count++;
                counter++;
            }
        } catch (NullPointerException nullPointerException) {
            JOptionPane.showMessageDialog(SaleItemForm.this, "Please Select one Item for Add", "Cannot Add", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void searchTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchItemDetails();
        }
    }//GEN-LAST:event_searchTextKeyPressed

    private void setDiscountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setDiscountLabelMouseClicked
        discountField.setEditable(true);
        discountField.requestFocus();
    }//GEN-LAST:event_setDiscountLabelMouseClicked

    private void qtyTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyTextMousePressed
        qtyText.setText(null);
    }//GEN-LAST:event_qtyTextMousePressed

    private void searchTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusLost
        //searchText.setText("Start Typing Or Scanning");
    }//GEN-LAST:event_searchTextFocusLost

    private void discountFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            setTotal();
        }
    }//GEN-LAST:event_discountFieldKeyPressed

    private void doPaymentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doPaymentLabelMouseClicked
        PaymentForm newPayment = new PaymentForm(this,grossTotal,billNumberLabel.getText());
        newPayment.setVisible(true);
    }//GEN-LAST:event_doPaymentLabelMouseClicked

    private void qtyTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyTextFocusGained
        qtyText.setText(null);
    }//GEN-LAST:event_qtyTextFocusGained

    private void deleteLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLabelMouseClicked
        if (DeleteSaleItem.getItemCode() != null) {
            String deleteItemCode = DeleteSaleItem.getItemCode();
            SelectedItemPanel deletePanel = DeleteSaleItem.getItemPanel();
            Iterator<SaleItem> itr = saleItemList.iterator();
            while (itr.hasNext()) {
                SaleItem item = itr.next();
                if (item.getItemCode().equals(deleteItemCode)) {
                    itr.remove();
                    setTotal();
                    deletePanel.setBackground(new Color(255, 204, 204));
                }
            }
            setDefaults();
        }else{
            JOptionPane.showMessageDialog(SaleItemForm.this, "Please Select One Item to Delete", "Select Item", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_deleteLabelMouseClicked

    private void qtyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTextActionPerformed

    private void qtyTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTextKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(qtyText.getText().isEmpty()){
                JOptionPane.showMessageDialog(SaleItemForm.this, "Please Enter the Correct Quantity", "Quantity Must Enter", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_qtyTextKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addItemLabel;
    private static javax.swing.JLabel billNumberLabel;
    private static javax.swing.JLabel dateLabel;
    private javax.swing.JLabel deleteLabel;
    private static javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField discountField;
    private static javax.swing.JLabel discountLabel;
    private javax.swing.JLabel doPaymentLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel orderItemsPanel;
    private javax.swing.JPanel payPanel;
    private javax.swing.JLabel paymentLabel;
    private static javax.swing.JLabel priceLabel;
    private static javax.swing.JTextField qtyText;
    private static javax.swing.JLabel salesPersonIdLabel;
    private javax.swing.JLabel salesPersonLabel;
    private javax.swing.JTextField searchText;
    private javax.swing.JLabel setDiscountLabel;
    private javax.swing.JLabel subTotalLabel;
    private static javax.swing.JLabel taxLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
    
    //Get Searched Item from the Database
    private SellInventoryItem searchItemDetails() {
        String code = searchText.getText();
        SellInventoryItem  detailsForSale = null;
        try {
            detailsForSale = InventoryItemController.getDetailsForSale(code);
            
            if (detailsForSale != null) {
                descriptionLabel.setText(detailsForSale.getProductName());
                priceLabel.setText(Double.toString(detailsForSale.getRetailPrice()));
                discountLabel.setText(Double.toString(detailsForSale.getDiscount()));
            }else{
                JOptionPane.showMessageDialog(HomeForm.getInstance(), "No Such Item", "Item Not Found", JOptionPane.ERROR_MESSAGE);
                setDefaults();
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SaleItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return detailsForSale;
    }
    
    //Generate next Invoice number
    private void setInvoieNumber() {
        try {
            String nextBillNumber = SaleController.getNextBillNumber();
            billNumberLabel.setText(nextBillNumber);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SaleItemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SaleItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //Get date from the System
    private void setBillDate() {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date curDate = new Date();
        String format = simpleDateFormat.format(curDate);
        dateLabel.setText(format);
    }

    //Set the total of currennt sale
    private void setTotal() {
        subTotal = 0;
        subDiscount = 0;
        double billDiscount = 0;
        for (SaleItem saleItem : saleItemList) {
            subTotal += saleItem.getTotalAmount();
            subDiscount += saleItem.getDiscount();
        }

        subTotalLabel.setText(Double.toString(subTotal));
        try {
            billDiscount = Double.parseDouble(discountField.getText());
        } catch (NumberFormatException ex) {
        }
        grossTotal = (subTotal - billDiscount) + tax;
        totalLabel.setText(Double.toString(grossTotal));
        paymentLabel.setText(Double.toString(grossTotal));
        totalDiscount = billDiscount + subDiscount;
    }
    
    //Retrive the last sale id from database and generate new sale id for every added item
    private String getSaleId(String currentId) {
        String nextSaleId = null;

        if (currentId == null) {
            try {
                nextSaleId = SaleItemController.getNextSaleId();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SaleItemForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(SaleItemForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            return nextSaleId;
        } else {
            nextSaleId = IDGenerator.getNextSaleId(currentId);
        }

        return nextSaleId;
    }
    
    //This method runs after one item added to majorItemsPanel
    public void setDefaults() {
        searchText.requestFocus();
        searchText.setText(null);
        qtyText.setText("1");
        priceLabel.setText("0.0");
        discountLabel.setText("0.0");
        descriptionLabel.setText(null);
    }

    public void setPanelDefaults() {
        saleItemList.clear();
        orderItemsPanel.removeAll();
        orderItemsPanel.repaint();
        orderItemsPanel.revalidate();
    }

}
